apiVersion: v1
kind: Service
metadata:
  name: {{ template "rainloop.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "rainloop.name" . }}
    chart: {{ template "rainloop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "rainloop.name" . }}
    release: {{ .Release.Name }}
