name: Publish helm chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/**'         

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Run chart-testing (lint), ensuring a version bump
      id: lint
      uses: helm/chart-testing-action@v2.2.1
      with:
        config: .ci/ct-config.yaml
        command: lint

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        install_local_path_provisioner: true
      # Only build a kind cluster if there are chart changes to test.
      if: steps.lint.outputs.changed == 'true'

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v2.2.1
      with:
        command: install
        config: .ci/ct-config.yaml

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # See https://github.com/helm/chart-releaser-action/issues/6
    #- name: Install Helm
    #  run: |
    #    curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    #    chmod 700 get_helm.sh
    #    ./get_helm.sh

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"      

    - name: Update chart repo
      uses: mvasigh/dispatch-action@master
      with:
        # token: ${{ secrets.CR_TOKEN }}
        repo: charts
        owner: geek-cookbook
        event_type: chart_update
